
# Facebook Mini URL webapp by @arbkv

application: fb-mini-url
version: 1
runtime: python
api_version: 1

handlers:

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /fb_mu.css
  static_files: static/fb_mu.css
  upload: static/fb_mu.css

- url: /.*
  script: index.py
